# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attention',
            table='attention',
        ),
    ]
