# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0005_auto_20160921_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
