#!/bin/bash

NAME="hawkapi"                                 # Name of the application
DJANGODIR=/var/www/hawkapi        # Django project directory
SOCKFILE=/var/www/hawkapi/hawkeye/gunicorn.sock    # we will communicte using this unix socket
USER=root                                           # the user to run as
GROUP=root                                          # the group to run as
NUM_WORKERS=4                                         # how many worker processes should Gunicorn spawn
TIMEOUT=480
DJANGO_SETTINGS_MODULE=hawkeye.settings.debug 
#DJANGO_SETTINGS_MODULE=hawkeye.settings.production    # which settings file should Django use
DJANGO_WSGI_MODULE=hawkeye.wsgi                    # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
    --name $NAME \
  --workers $NUM_WORKERS \
  --worker-class gevent \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --timeout $TIMEOUT \
  --log-level=debug \
  --log-file=/tmp/gunicorn-hawkapi.log \


#--access-logformat = %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
#--access-logformat = "remote": "%(h)s", "date": "%(t)s", "method": "%(m)s", "status": "%(s)s", "url": "%(U)s", "query": "%(q)s", "referer" :%(f)s", "user-agent" : "%(a)s", "request_time" : "%(L)s"


