# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160907_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairong',
            name='metadata',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
