# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160913_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliEnterpriseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=32)),
                ('comp', models.CharField(max_length=128)),
                ('base', models.TextField()),
                ('profile', models.TextField()),
                ('relation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ali_enterprise_data',
            },
        ),
        migrations.CreateModel(
            name='AliEnterpriseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicode', models.CharField(max_length=32)),
                ('comp', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ali_enterprise_list',
            },
        ),
    ]
