# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alienterprisedata_alienterpriselist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=15)),
                ('meal', models.CharField(max_length=10)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checkthree',
            },
        ),
    ]
