# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20161125_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkthree',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkthree',
            name='meal',
            field=models.CharField(max_length=15),
        ),
    ]
