# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.TextField()),
                ('role', models.CharField(default='user', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
