# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20160907_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
